<?php
/**
 * @file
 * A description of what your module does.
 * @author Prasanth Sukhapalli
 */

/**
 * Implements hook_help().
 * @param $path
 * @param $arg
 * @return array|mixed|string|null
 */
function access_gdrive_help($path, $arg)
{
    switch ($path) {
        case "admin/help#access_gdrive":
            return t("Module to provide permissions to Google Drive Files while submitting webforms.");
            break;
    }
}


/**
 * Implements hook_menu().
 */
function access_gdrive_menu()
{
    $items = array();
    $items['node/%webform_menu/webform/access_gdrive'] = array(
        'title' =>  'GDrive File Access',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('access_gdrive_edit_form', 1),
        'access arguments' => array('access administration pages'),
        'file' => 'includes/access_gdrive.fileset.inc',
        'type' => MENU_LOCAL_TASK,
    );

    $items['admin/config/content/access_gdrive'] = array(
        'title' =>  'GDrive Access Admin Settings',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('access_gdrive_admin_form'),
        'access arguments' => array('access administration pages'),
        'file' => 'includes/access_gdrive.fileset.inc',
        'type' => MENU_NORMAL_ITEM,
    );

    return $items;
}

/**
 * Implements hook_form_alter().
 */
function access_gdrive_form_alter(&$form, &$form_state, $form_id)
{
  if(isset($form['#node']->nid) && $form_id == 'webform_client_form_'.$form['#node']->nid){
    array_push($form['#submit'], 'access_gdrive_webform_submit');
  }
}

/**
 * Implements access_gdrive_webform_submit().
 * @param $form
 * @param $form_state
 */
function access_gdrive_webform_submit($form, &$form_state)
{
  include_once( drupal_get_path('module', 'access_gdrive') . '/access_gdrive.class.inc' );
  $config_details = db_query("SELECT * FROM {access_gdrive}")->fetchAssoc();
  $node_details = db_query("SELECT * FROM {access_gdrive_files} WHERE nid = :nid", array(":nid" => $form['#node']->nid))->fetchAssoc();
  $email = $form_state['values']['submitted'][$node_details['component_value']];
  $obj = new Drive_Client( $config_details['app_name'], $config_details['credentials'], $config_details['access_token']);
  $status = $obj->provide_file_permission($node_details['file_ids'], $email, 'user', 'reader');
  if($status){
    drupal_set_message("Permission provided for the Requested Files.");
  }
  $rows_updated = db_update('access_gdrive')->fields(array(
    'access_token' => json_encode($obj->get_token()),
  ))->execute();
  drupal_set_message('Rows updated' . $rows_updated);
}
